FAADemo/Controllers/AirlineController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using FAADemo.Public.ViewModels;
using FAADemo.Svc.Services;

namespace FAADemo.Controllers
{
    public class AirlineController : ApiController
    {
        private readonly IAirlineService _airlineService;
        public AirlineController(IAirlineService airlineService)
        {
            _airlineService = airlineService;
        }

        public List<AirlineVm> Get()
        {
            return _airlineService.GetAllAirlines();
        }

        public AirlineDetailsVm Get(Guid id)
        {
            return _airlineService.GetAirline(id);
        }

        public HttpResponseMessage Post(HttpRequestMessage request, AirlineVm airline)
        {
            List<string> errors = new List<string>();
            if (ModelState.IsValid)
            {
                _airlineService.AddAirline(airline);
                return request.CreateResponse(HttpStatusCode.OK);
            }
            else
            {
                errors.AddRange(PostErrors());
            }
            return request.CreateResponse(HttpStatusCode.BadRequest, errors);
        }

        private IEnumerable<string> PostErrors()
        {
            return ModelState.Values.SelectMany(v => v.Errors.Select(e => e.ErrorMessage));
        }
    }
}

FAADemo/Controllers/AirportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using FAADemo.Public.ViewModels;
using FAADemo.Svc.Services;

namespace FAADemo.Controllers
{
    public class AirportController : ApiController
    {
        private readonly IAirportService _airportService;
        public AirportController(IAirportService airportService)
        {
            _airportService = airportService;
        }

        public List<AirportVm> Get()
        {
            return _airportService.GetAllAirports();
        }

        public AirportDetailsVm Get(Guid id)
        {
            return _airportService.GetAirport(id);
        }

        public HttpResponseMessage Post(HttpRequestMessage request, AirportVm airport)
        {
            List<string> errors = new List<string>();
            if (ModelState.IsValid)
            {
                _airportService.AddAirport(airport);
                return request.CreateResponse(HttpStatusCode.OK);
            }
            else
            {
                errors.AddRange(PostErrors());
            }
            return request.CreateResponse(HttpStatusCode.BadRequest, errors);
        }

        private IEnumerable<string> PostErrors()
        {
            return ModelState.Values.SelectMany(v => v.Errors.Select(e => e.ErrorMessage));
        }
    }
}

FAADemo/Controllers/FlightBookerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FAADemo.Controllers
{
    public class FlightBookerController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

    }
}

FAADemo/Controllers/FlightController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Runtime.InteropServices;
using System.Web.Http;
using FAADemo.Public.ViewModels;
using FAADemo.Svc.Services;

namespace FAADemo.Controllers
{
    public class FlightController : ApiController
    {
        private readonly IFlightService _flightService;

        public FlightController(IFlightService flightService)
        {
            _flightService = flightService;
        }
        public List<SpecialFlightVm> Get()
        {
            return _flightService.GetSpecialFlights();
        }

        public FlightDetailsVm Get (Guid id)
        {
            return new FlightDetailsVm();
        }
    }
}

namespace FAADemo.Public.ViewModels
{
}

FAADemo/Controllers/PassengerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using FAADemo.Public.ViewModels;
using FAADemo.Svc.Services;

namespace FAADemo.Controllers
{
    public class PassengerController : ApiController
    {
        private readonly IPassengerService _passengerService;

        public PassengerController(IPassengerService passengerService)
        {
            _passengerService = passengerService;
        }

        public HttpResponseMessage Post(HttpRequestMessage request, PassengerVm model)
        {
            List<string> errors = new List<string>();
            if (ModelState.IsValid)
            {
                try
                {
                    _passengerService.AddPassenger(model);
                    return request.CreateResponse(HttpStatusCode.OK);
                }
                catch (Exception ex)
                {
                    errors.Add(ex.Message);
                }
            }
            else
            {
                errors.AddRange(PostErrors());
            }

            return request.CreateResponse(HttpStatusCode.BadRequest, errors);

        }

        private IEnumerable<string> PostErrors()
        {
            return ModelState.Values.SelectMany(v => v.Errors.Select(e => e.ErrorMessage));
        }
    }
}

FAADemo/Views/FlightBooker/Index.cshtml
@{
    Layout = null;
    ViewBag.Title = "Welcome";
}
<!DOCTYPE html>
<html ng-app="flightBooker">
<head>
    <base href="/"/>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Book A Flight With Us</title>
    <link rel="stylesheet" href="http://kendo.cdn.telerik.com/2015.2.805/styles/kendo.common.min.css">
    <link rel="stylesheet" href="http://kendo.cdn.telerik.com/2015.2.805/styles/kendo.rtl.min.css">
    <link rel="stylesheet" href="http://kendo.cdn.telerik.com/2015.2.805/styles/kendo.default.min.css">
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/FlightBooker/Index" class="navbar-brand">Flight Booker</a>)
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="/FlightBooker/Index">Home</a></li>
                    <li>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Flights<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="/Flight/Search">Search Flights</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Passengers<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="/Passenger/Add">Add Passenger</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Airports<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="/Airport/Detail">View Airports</a></li>
                            <li><a href="/Airport/Edit">Edit Airport</a></li>
                            <li><a href="/Airport/Add">Add Airport</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Airlines<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="/Airline/Detail">View Airlines</a></li>
                            <li><a href="/Airline/Add">Add Airline</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
<div class="container body-content">
    <div ng-view></div>
    <hr/>
    <footer>
        <p>&copy; @DateTime.Now.Year - My ASP.NET Application </p>
    </footer>
</div>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/flightBooker")
</body>
</html>

FAADemo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html ng-app="flightBooker">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/angular")
    @Scripts.Render("~/bundles/flightBooker")
    @RenderSection("scripts", required: false)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Flight Booker", "Index", "FlightBooker", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "FlightBooker")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>
</body>
</html>